### ISSUE TITLE
fatal: clone of 'git@github.com:jameshanlon/verilator.git'

### ISSUE THREAD

**Issue by psychedel** [jameshanlon/netlist-paths#2]
- During git submodule update --init --recursive:
>>
submodule 'verilator' (git@github.com:jameshanlon/verilator.git) registered for path 'verilator'
Cloning into '/netlist-paths/verilator'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Build and test pass well with https://github.com/jameshanlon/verilator.git
 (branch dump-netlist-graph)

**Comment by jameshanlon** [comment]
Thanks for reporting the issue. It should be fixed with e2f0c8bc6e.

Cheers,
Jamie
